### ISSUE TITLE
关于新手配置问题

### ISSUE THREAD

**Issue by petsa** [progrape/gulp-spriters#1]
hi,你好，在我的工作流中配置了gulp-spriters没发现有执行合并雪碧图的效果，来github这边想跑一下测试例子，test跑不通，是需要什么环境呢？我node v4.4.2运行 test的时候报错

**Comment by progrape** [comment]
@petsa hi，报什么错误信息？我本地跑 test 目录下的可以合并出图片来，`test/output` 目录下就有合并的图片

**Comment by petsa** [comment]
@progrape 
gulp-spriters ➤ node test/test.js                                   git:master*
/Users/petsa/Documents/vip-work/vpalstaticDev/bobo/node_modules/gulp-spriters/test/test.js:13
describe('gulp-spriters', function () {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (/Users/petsa/Documents/vip-work/vpalstaticDev/bobo/node_modules/gulp-spriters/test/test.js:13:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by petsa** [comment]
@progrape 
运行test不行，我在项目里面配置已经能实现图片合并了，原来产出的路径跟css同一个目录，之前没注意到
1.刚测了下margin参数设置了20，最终产出的图并没有效果
2.另外产出的图片有设置可以调整位置吗

下面是我项目中的配置，是不是有什么问？
gulp.task('style', function () {
  return gulp.src(path.less + '*_/_.less')
    .pipe(sourcemaps.init())
    .pipe(less())
    .pipe(sourcemaps.write({includeContent: false}))
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(autoprefixer())
    // .pipe(minifyCSS())
    .pipe(sourcemaps.write('.'))
    .pipe(spriters({
        margin: 20
    }))
    .pipe(gulp.dest(path.build + 'css/'));
});

**Comment by progrape** [comment]
@petsa 从报错信息看，是说 `describe` 方法未定义，这个方法是测试框架提供的，`test.js` 文件不能直接用 `node test/test.js` 命令来执行，需要安装 `mocha` ，然后通过 `npm test` 来运行。

`margin` 参数暂时没有起作用，抱歉。

图片的位置，是通过二叉树排序算法计算出来的，由 `bin-pack` 模块实现，比横向排列或者纵向排列要优，所以应该不需要去调整图片的位置。

**Comment by petsa** [comment]
@progrape 谢谢你耐心的解答，我说的图片位置不是雪碧图上面合并的位置，是最终输出spriter.png这张图的位置

**Comment by progrape** [comment]
明白，目前图片输出的名称和路径，文件名是 `xxx_z.png` 或 `xxx_z@2x.png` ，路径是和 css 文件同一个目录，这样做主要是我个人的一种习惯吧。目前这份代码是不支持调整的，如果要支持调整，可以把代码稍作修改，传入参数，在适当的位置调用传入的参数就行了的。
